let humanscore = 0;
let computerscore = 0;

const choice = ["ROCK", "PAPER", "SCISSOR"];  //here we are  just giving the  choices wrapped in an array 
const randomBufer = new  Uint32Array(1); //we are creating a random buffer of 32 bit unsigned integer with the size of 1, which will hold our random number generated by the crypto API.
window.crypto.getRandomValues(randomBufer);  //we are using the crypto API to fill our random buffer with a random number. The getRandomValues method generates cryptographically strong random values and fills the provided array with them. In this case, it will fill our randomBufer with a single random number.
const randomNumber = randomBufer[0] / (0xFFFFFFFF + 1); //we are dividing the random number by 0xFFFFFFFF + 1 to normalize it to a value between 0 and 1. This is because the random number generated by getRandomValues can be any value between 0 and 0xFFFFFFFF (inclusive), so dividing by 0xFFFFFFFF + 1 ensures that we get a decimal value in the range of [0, 1).   
const computerChoice = choice[Math.floor(randomNumber * choice.length)]; //we are multiplying the random number by the length of the choice array (which is 3) to scale it to the range of [0, 3). Then we are using Math.floor to round it down to the nearest whole number, which will give us an index of either 0, 1, or 2. Finally, we are using that index to select a choice from the choice array, which will be the computer's choice in the game.
console.log("Computer choice: " + computerChoice);  //we are logging the computer's choice to the console so that we can see what it is. This will help us in testing and debugging our game logic later on.

//making a functtionn to take get human choice
function getHumanChoice() {
    humanChoice = humanChoice.toUpperCase();
    let humanChoice = prompt("Enter your choice (ROCK, PAPER, SCISSOR):"); 
    
    return humanChoice;
}
console.log("Human choice: " + getHumanChoice()); 



function  playGame() {
    function playRound(humanChoice, computerChoice) {
    if (humanChoice === computerChoice) {
        return "It's a tie!";
    } else if (
        (humanChoice === "ROCK" && computerChoice === "SCISSOR") ||
        (humanChoice === "PAPER" && computerChoice === "ROCK") ||
        (humanChoice === "SCISSOR" && computerChoice === "PAPER")
    ) {
        humanscore++;
        return "You win this round!";
    } else {
        computerscore++;
        return "Computer wins this round!";
    }
}

const humanChoice = getHumanChoice();
const result = playRound(humanChoice, computerChoice);
console.log(result);
console.log("Human Score: " + humanscore);
console.log("Computer Score: " + computerscore);


}

for(let i = 0; i < 5; i++) {
    playGame();
}